#spring.application.name=practice-jdbc

spring:
  application:
    name: practice-jdbc
  datasource:
    url: jdbc:h2:mem:userDB
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2


server:
  port: 8081